#!/usr/bin/env bash

# Data commits
CONVCOMMIT_LIST=$(git log -s --format=%s master..$1  | grep --color=never -E '^(build|ci|chore|feat|fix|refactor|style|docs|test)?\([a-z]*\): (.{1,50}$)');
ALLCOMMIT_LIST=$(git log -s --format=%s master..$1 );

CONVCOMMIT_COUNT=$(git log -s --format=%s master..$1  | grep --color=never -E '^(build|ci|chore|feat|fix|refactor|style|docs|test)?\([a-z]*\): (.{1,50}$)' | wc -l);
ALLCOMMIT_COUNT=$(git log -s --format=%s master..$1  | wc -l);


DIFF=$(diff  <(echo -e "$ALLCOMMIT_LIST"\n) <(echo -e "$CONVCOMMIT_LIST"\n));
DIFF_COUNT=$(($ALLCOMMIT_COUNT - $CONVCOMMIT_COUNT));
# Styles
#https://stackoverflow.com/questions/48536791/error-tput-no-value-for-term-and-no-t-specified
[[ ${TERM}=="" ]] && TPUTTERM='-T xterm-256color' TPUTTERM=''
declare -r red=`tput${TPUTTERM} setaf 1`;
declare -r declare -r green=`tput${TPUTTERM} setaf 2`;
declare -r blue=`tput${TPUTTERM} setaf 4`;
declare -r yellow=`tput${TPUTTERM} setaf 3`;

# whiteBg=`tput${TPUTTERM} setab 8`

declare -r bold=$(tput${TPUTTERM} bold);
declare -r underline=`(tput${TPUTTERM} sgr 0 1)`;

declare -r reset=`tput${TPUTTERM} sgr0`;
echo ${DIFF_COUNT};
if [ ${DIFF_COUNT} -ge 1 ];then
  echo ${underline}${red}  "${bold} ${DIFF_COUNT} no-conventionnal commit found" ${reset};
  echo ${yellow} "-------------" ${reset};
  echo ${red}"$DIFF" ${reset};
  echo ${yellow} "-------------" ${reset};
  echo ${red} "please try => ${yellow}/!\one by one commit/!\\"${rest};
  echo ${red} "1- ${bold}${whiteBg}git rebase -i HEAD~${ALLCOMMIT_COUNT}"${reset};
  echo ${red} "2- ${bold}${whiteBg}replace pick by reward on the commit, save & quit" ${reset};
  echo ${red} "3- ${bold}${whiteBg}fix the commit message with convientionnal format, save & quit " ${reset};
  echo ${red} "${bold}${whiteBg}Et voila !" ${reset};
  echo "";
  echo ${red} "${bold}<-- don't be afraid of rebase we believe in you -->";
  exit 1;
else
  echo ${green} ${bold} "all commit are conventionnals" ${reset};
  echo ${blue} "-------------" ${reset};
  echo ${green} "$CONVCOMMIT_LIST" ${reset};
  echo ${blue} "-------------" ${reset};
  echo ${bold} ${blue} "good job !" ${reset};
  exit 0;
fi